### ISSUE TITLE
Buttons not showing up

### ISSUE THREAD

**Issue by RaspberryKitty1** [notPlancha/Volume-Profiles-Spicetify-Extension-v2#1]
Spotify for Windows
1.1.83.956.gbe7ea9a7

spicetify v2.9.7  

![image](https://user-images.githubusercontent.com/28585042/164993251-58500d22-e4c3-4e8f-948c-7d215adebbf5.png)
even with default theme
![image](https://user-images.githubusercontent.com/28585042/164993286-552f7222-e9ce-4c92-9044-582dd7519c9d.png)

**Comment by notPlancha** [comment]
if you downloaded through the marketplace try installing through the file directly, I updated it recently and it might take some time for the marketplace to cache it.

**Comment by RaspberryKitty1** [comment]
same results....
both ways...

**Comment by notPlancha** [comment]
I've update it, check if now working
It shouldn't break with an update anymore too,

**Comment by RaspberryKitty1** [comment]
![image](https://user-images.githubusercontent.com/28585042/165159177-c6bb5b8a-abef-4506-81ce-07c9ea6eea93.png)
still same thing...

**Comment by notPlancha** [comment]
would you mind sharing here a screenshot of your console as well a screenshot of your sources, with the extensions  (both in the devtools)? Like this
![image](https://user-images.githubusercontent.com/31565873/165163913-1ea80464-1f9f-48ad-b981-8d0f4f142d85.png)
![image](https://user-images.githubusercontent.com/31565873/165164000-c2cffbfa-3ba5-49c4-9f9d-a449a2961cf9.png)

**Comment by RaspberryKitty1** [comment]
how would i access the devtools?

**Comment by RaspberryKitty1** [comment]
![image](https://user-images.githubusercontent.com/28585042/165166903-0eae649f-94e5-488c-a4ad-3fa35423dc04.png)
![image](https://user-images.githubusercontent.com/28585042/165167108-a9345d78-34a0-4fac-a92c-ca649b931814.png)
looks like it did not even attempt to load
but its in the spitified config
extensions            = popupLyrics.js|volume-profiles

**Comment by notPlancha** [comment]
it looks like the .js is missing

**Comment by RaspberryKitty1** [comment]
seems that was the issue... but it seems to work now thanks :)
also the marketplace version seems to work now as well. (neither was working at the time of issue creation)

**Comment by notPlancha** [comment]
the marketplace issue should be the caching issue so yea
