### ISSUE TITLE
Unavailable on Marketplace

### ISSUE THREAD

**Issue by non-bin** [notPlancha/Volume-Profiles-Spicetify-Extension-v2#2]
I can't see any errors in the manifest, so I'm not sure why it's not showing up for me, has anyone else had this problem?

**Comment by notPlancha** [comment]
Are you saying that the extension doesn't appear in the marketplace to install or that after installing from the marketplace it doesn't do anything?

**Comment by notPlancha** [comment]
closed due to inactivity, maybe I'll check it later if I actually find it missing in the marketplace

**Comment by notPlancha** [comment]
I found it so

**Comment by non-bin** [comment]
doesn't apear in the list

**Comment by notPlancha** [comment]
![image](https://user-images.githubusercontent.com/31565873/195090237-99879171-d131-4f8b-9a84-1b8f766ac558.png)
If you can't actually find me do me a favour and tell me what you did to get to that conclusion , from a restored spotify stand point
